workflows:
  android-ios-web:
    name: SIDL CORPORATION App Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Set up code signing
      - script: |
      - app-store-connect fetch-signing-files "fr.sidlcorporation.sidlcorporation" --type IOS_APP_STORE --create
      - keychain initialize

      - name: Set up local properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Install dependencies
        script: flutter pub get

      - name: Generate splash screens and icons
        script: |
          flutter pub run flutter_launcher_icons
          flutter pub run flutter_native_splash:create

      - name: Flutter analyze
        script: flutter analyze

      - name: Flutter build iOS
        script: |
          find . -name "Podfile" -execdir pod install \;
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - contact@sidl-corporation.fr