workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.votreapp.identifiant
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Flutter packages get
        script: flutter packages pub get
      - name: Install CocoaPods
        script: cd ios && pod install
      - name: Flutter build iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID