workflows:
  ios-build:
    name: SIDL CORPORATION iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Set up code signing
        script: |
          app-store-connect fetch-signing-files "fr.sidlcorporation.sidlcorporation" --type IOS_APP_STORE --create
          keychain initialize

      - name: Install dependencies
        script: flutter pub get

      - name: Désactiver toutes les capacités de notification
        script: |
          # Supprimer les modes d'arrière-plan
          /usr/libexec/PlistBuddy -c "Delete :UIBackgroundModes" ios/Runner/Info.plist 2>/dev/null || true

          # Supprimer tout entitlement de notification
          touch ios/Runner/Runner.entitlements
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
          </dict>
          </plist>' > ios/Runner/Runner.entitlements

      - name: Generate splash screens and icons
        script: |
          flutter pub run flutter_launcher_icons
          flutter pub run flutter_native_splash:create

      - name: Flutter analyze
        script: flutter analyze

      - name: Flutter build iOS
        script: |
          find . -name "Podfile" -execdir pod install \;
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - contact@sidl-corporation.fr