name: sidlcorporation
description: "Application officiel de l'entreprise SIDL CORPORATION"
publish_to: 'SIDL CORPORATION'
version: 0.1.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Interface utilisateur
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.6.0

  # Navigation
  webview_flutter: ^4.2.2
  url_launcher: ^6.1.14

  # Gestion d'état et stockage
  provider: ^6.0.5
  shared_preferences: ^2.2.1

  # Requêtes réseau et API
  http: ^1.1.0
  connectivity_plus: ^4.0.2
  xml: ^6.3.0

  # Utilitaires
  intl: ^0.18.1
  package_info_plus: ^4.1.0
  device_info_plus: ^9.0.3
  path_provider: ^2.1.1

  # Notifications
  flutter_local_notifications: ^15.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Configuration Flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Configuration du splash screen
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  fullscreen: false
  ios: true
  web_image_mode: center

# Configuration des icônes de l'application
flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  ios: true
  remove_alpha_ios: true