name: sidlcorporation
description: "Application officiel de l'entreprise SIDL CORPORATION"
publish_to: 'SIDL CORPORATION'
version: 0.0.1+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Interface utilisateur
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  # app_tracking_transparency: ^2.0.3

  # Gestion d'état et stockage
  provider: ^6.1.1
  shared_preferences: ^2.2.2

  # Connectivité et navigation
  internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.2.1

  # Configuration de l'application
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.14.3

# Configuration Flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Configuration du splash screen
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  fullscreen: true
  ios: true
  web_image_mode: center

# Configuration des icônes de l'application
flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  ios: true
  remove_alpha_ios: true