name: sidlcorporation
description: "Application officiel de l'entreprise SIDL CORPORATION"
publish_to: 'SIDL CORPORATION' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Interface utilisateur
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  # app_tracking_transparency: ^2.0.3

  # Gestion d'état et stockage
  provider: ^6.1.1
  shared_preferences: ^2.2.2

  # Connectivité et navigation
  # connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.2.1

  # Configuration de l'application
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Configuration Flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Configuration du splash screen
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#121212"

  image: assets/images/logo-light.png
  image_dark: assets/images/logo-dark.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#121212"
    image: assets/images/logo-light.png
    image_dark: assets/images/logo-dark.png

  fullscreen: true

  android: false
  ios: true
  web: false

  web_image_mode: center

# Configuration des icônes de l'application
flutter_launcher_icons:
  image_path: "assets/images/logo.png"

  android: "launcher_icon"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "assets/images/logo.png"
  min_sdk_android: 21

  ios: true
  remove_alpha_ios: true

  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#1D9BF0"