name: sidlcorporation
description: "Application officiel de l'entreprise SIDL CORPORATION"
publish_to: 'SIDL CORPORATION'
version: 0.0.1+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

# Configuration Flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Configuration du splash screen
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  fullscreen: true
  ios: true
  web_image_mode: center

# Configuration des icônes de l'application
flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  ios: true
  remove_alpha_ios: true